name: todo_challenge
description: A simple todo app in Flutter with a minimalistic design

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation:
  cupertino_icons: ^1.0.2
  firebase_core: ^1.7.0
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.0-dev.7
  cloud_firestore: ^2.5.3
  json_annotation: ^4.1.0
  equatable: ^2.0.3
  firebase_auth: ^3.1.2
  google_sign_in: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  freezed:
  flutter_lints: ^1.0.0
  json_serializable: ^5.0.2

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.otf
        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700
